services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - postgres-db-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=5GB"
      - "-c"
      - "work_mem=256MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "effective_cache_size=15GB"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "checkpoint_timeout=10min"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "max_wal_size=8GB"
      - "-c"
      - "min_wal_size=2GB"
      - "-c"
      - "wal_compression=on"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  
  pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      ../.env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  
volumes:
  postgres-db-volume: